workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Unpack project and Build APK
        script: |
          unzip -o offline_ai_app-3.zip
          if [ -d "android" ]; then
            cd android && ./gradlew assembleRelease
          else
            find . -maxdepth 2 -name "gradlew" -exec chmod +x {} \;
            find . -maxdepth 2 -name "gradlew" -execdir ./gradlew assembleRelease \;
          fi
    artifacts:
      - "**/build/outputs/**/*.apk"
