workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Build Android APK
        script: |
          unzip -o offline_ai_app-3.zip
          cd offline_ai_app/android
          chmod +x gradlew
          ./gradlew assembleRelease
    artifacts:
      - offline_ai_app/android/app/build/outputs/**/*.apk
